# Generated by Django 4.0.3 on 2022-05-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phuongtien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, max_length=256, null=True)),
                ('name', models.TextField(blank=True, max_length=256, null=True)),
                ('model', models.TextField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
