# Generated by Django 4.0.3 on 2022-05-16 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QL', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phuongtien',
            name='model',
        ),
        migrations.RemoveField(
            model_name='phuongtien',
            name='name',
        ),
    ]
