# Generated by Django 4.0.3 on 2022-05-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QL', '0002_remove_phuongtien_model_remove_phuongtien_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='phuongtien',
            name='model',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='phuongtien',
            name='name',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
