# Generated by Django 4.0.3 on 2022-05-16 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QL', '0003_phuongtien_model_phuongtien_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='phuongtien',
            new_name='Vehicles',
        ),
    ]
